language: java
sudo: required
jdk:
  - openjdk8
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/setupenvironment.sh
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh confidentiality releng/edu.kit.kastel.scbs.confidentiality.updatesite.aggregated final KASTEL-SCBS updatesite

notifications:
  slack:
    secure: XTp76ZsrHdHe1qwD2tQ07VJU99b91hIybNPKwO9wiXGxCqKpDjrCjxhvcLbhitgrXtkaD+W27LIW4xAdoqDfZf4wxSrDGjklPvatFzr7AYp2KnFqTsyZcYsYNlpsT+e4pqil6PHRUR8sRKxajNczlx7YvdNOm5etxRhxBJZEA3Bgp0Dga3kaFYn0HT0C8PypvY2Vzes8HKU0Pix/PBuFTC0DYinrc7gcDvvj1qVCF8Q/BfQSHDZdXdHMRb4cQGbuFIStSf6B98zdMDDRjglhMGqC2Hrkua/8Hk5Futr8k8P2A/Ax/viQ0kwipv703/62/gOHgwGZ4u2OBv/PJQ4kps74xTaq3NcekriAJrfsyxBFyLTi8A6w8BoRhxS5xejuVoXMTPf9Txyk9TuViOc0LJ5m5ijmptzxt3QkBRwk7zeLvWSPEdTlu0OUY7LdJ0epLRkOoMCalCQE6qFvNMqYGvROgnyUQ1Li57OzPfJdRscF7r2WGt41waT3KjcCFJHrSujrZ6zkAQdQkjZP9Y+K/1ZfPSR3XIZKUrnH9aKqg5UEwVDkRh+5aYXb6pQ+AYCpTDxBbJigwtNa4uIaRRVUxYy65fhcA0b7UhjfYjY1jAOJOnBimA0jiHhRDyGV75APSNuRWboNefGXJopdZ/hAnwScngsP/sO8aKLHdXHY31Y=